# Translations template for invenio-records-rest.
# Copyright (C) 2025 CERN
# This file is distributed under the same license as the
# invenio-records-rest project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: invenio-records-rest 2.4.1\n"
"Report-Msgid-Bugs-To: info@inveniosoftware.org\n"
"POT-Creation-Date: 2025-04-02 23:48+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: invenio_records_rest/config.py:262
msgid "Best match"
msgstr ""

#: invenio_records_rest/config.py:268
msgid "Most recent"
msgstr ""

#: invenio_records_rest/errors.py:51
msgid "Invalid query syntax."
msgstr ""

#: invenio_records_rest/errors.py:67
#, python-format
msgid "Style %(style)s could not be found."
msgstr ""

#: invenio_records_rest/errors.py:93
msgid "PID does not exist."
msgstr ""

#: invenio_records_rest/errors.py:105
msgid "PID is not registered."
msgstr ""

#: invenio_records_rest/errors.py:117
msgid "PID has been deleted."
msgstr ""

#: invenio_records_rest/errors.py:129
#, python-format
msgid "No object assigned to %(pid)s."
msgstr ""

#: invenio_records_rest/errors.py:142
#, python-format
msgid "Invalid redirect - pid_type %(pid_type)s endpoint missing."
msgstr ""

#: invenio_records_rest/errors.py:160
#, python-format
msgid "PID %(pid)s could not be resolved."
msgstr ""

#: invenio_records_rest/errors.py:174
#, python-format
msgid "Unsupported media type \"%(content_type)s\"."
msgstr ""

#: invenio_records_rest/errors.py:188
msgid "Could not load data."
msgstr ""

#: invenio_records_rest/errors.py:200
msgid "Could not patch JSON."
msgstr ""

#: invenio_records_rest/errors.py:213
#, python-format
msgid "Missing %(ctx_field)s context."
msgstr ""

#: invenio_records_rest/errors.py:228
#, python-format
msgid "No completions requested.%(options)s"
msgstr ""

#: invenio_records_rest/errors.py:243
#, python-format
msgid "Validation error: %(error)s."
msgstr ""

#: invenio_records_rest/errors.py:257
msgid "An internal server error occurred when handling the request."
msgstr ""

#: invenio_records_rest/views.py:66
msgid "The syntax of the search query is invalid."
msgstr ""

#: invenio_records_rest/views.py:441
msgid "The query parameters from and page must not be used at the same time."
msgstr ""

#: invenio_records_rest/views.py:478
msgid "Invalid pagination parameters."
msgstr ""

#: invenio_records_rest/views.py:515
#, python-format
msgid "Maximum number of %(count)s results have been reached."
msgstr ""

